config/routes.rb
Rails.application.routes.draw do
  root 'input#index'
  post 'generate_bill', to: 'input#generate_bill'
  get '/products.json', to: 'products#index', defaults: { format: 'json' }
  resources :products
  get '/input/products_json', to: 'products#products_json'
end

app/controllers/input_controller.rb
# app/controllers/input_controller.rb
class InputController < ApplicationController
  def index
    # This action is responsible for displaying the input form to the user.
    # Retrieve necessary data for the form, such as product details, from the database.
    @products = Product.all # Replace with your actual product retrieval logic.
    @product_options = @products.map { |product| [product.name, product.id] }
    session[:line_items] ||= []
  end

  def generate_bill
    denominations_params = params[:denominations].permit!
    # Step 1: Retrieve user input from the form
    customer_email = params[:customer_email]
    product_ids = params[:product_ids]
    quantities = params[:quantities]
    cash_paid = params[:cash_paid].to_f

    # Step 2: Calculate the bill based on the input
    # Retrieve product details from the database based on product_ids.
    products = Product.where(id: product_ids)

    # Calculate the purchased price, tax, and total for each selected product based on quantities.
    line_items = calculate_line_items(products, quantities)

    # Calculate total price without tax
    total_price_without_tax = calculate_total_price(line_items)

    # Calculate total tax payable
    total_tax_payable = calculate_total_tax_payable(line_items)

    # Calculate the net price (total_price_without_tax + total_tax_payable)
    net_price = total_price_without_tax.to_f + total_tax_payable.to_f
    # Calculate the rounded down value
    rounded_down_value = net_price.round

    # Calculate the balance payable to the customer
    balance_payable_to_customer = cash_paid - rounded_down_value

    # Step 3: Handling Denominations
    # Process the customer's input for denominations and calculate the total amount of denominations
    @customer_denominations = denominations_params.reject { |_, quantity| quantity.blank? }.to_h
    total_denominations = calculate_total_denominations(@customer_denominations)

    # Calculate the balance amount based on denominations
    balance_based_on_denominations = total_denominations - cash_paid

    # Store the calculated denominations and balance in instance variables
    @total_denominations = total_denominations
    @balance_based_on_denominations = balance_based_on_denominations

    # Step 4: Display the bill
    # Pass the calculated bill details to the bill view for rendering.
    @customer_email = customer_email
    @line_items = session[:line_items]
    @total_price_without_tax = total_price_without_tax
    @total_tax_payable = total_tax_payable
    @net_price = net_price
    @rounded_down_value = rounded_down_value
    @balance_payable_to_customer = balance_payable_to_customer

    # Save or update the line_items in the session
    session[:line_items] = line_items
    line_items.each do |line_item|
      LineItem.create(
        product_id: line_item[:product_id],
        quantity: line_item[:quantity],
        purchased_price: line_item[:purchased_price],
        tax: line_item[:tax],
        tax_pay: line_item[:tax_pay],
        total: line_item[:total]
      )
    end
    @line_items = line_items
    @amount = @balance_payable_to_customer
    @five_hundred = (@amount / 500).floor
    @amount %= 500

    @fifty = (@amount / 50).floor
    @amount %= 50

    @twenty = (@amount / 20).floor
    @amount %= 20

    @ten = (@amount / 10).floor
    @amount %= 10

    @five = (@amount / 5).floor
    @amount %= 5

    @two = (@amount / 2).floor
    @amount %= 2

    @one = @amount.floor
    Bill.create(customer_email: @customer_email, total_price: @total_price_without_tax, total_tax_payable: @total_tax_payable, net_price: @net_price, rounded_down_value: @rounded_down_value, balance_payable_to_customer: @balance_payable_to_customer)
    render 'generate_bill'
  end

  private

  def calculate_line_items(products, quantities)
    line_items = []

    products.each_with_index do |product, index|
      # Retrieve product details
      product_id = product.id
      product_name = product.name
      unit_price = product.price
      tax_percentage = product.tax_percentage
      price = product.price

      # Retrieve quantity for the current product
      quantity = quantities[index].to_i

      # Calculate purchased price for the current product (unit_price * quantity)
      purchased_price = unit_price * quantity

      # Calculate tax for the current product (tax_percentage/100 * purchased_price)
      tax_pay = (tax_percentage.to_f / 100) * purchased_price

      # Calculate tax pay for the current product (tax * quantity)
      # tax_pay = tax * quantity

      # Create a line item hash for the current product
      line_item = {
        product_id: product_id,
        product_name: product_name,
        unit_price: unit_price,
        quantity: quantity,
        purchased_price: purchased_price,
        tax: tax_percentage, # Change to tax_percentage here
        tax_pay: tax_pay,
        total: purchased_price + tax_pay
      }

      # Add the line item to the array
      line_items << line_item
    end

    return line_items
  end

  def calculate_total_price(line_items)
    total_price_without_tax = 0

    line_items.each do |line_item|
      # Retrieve the purchased price for the current line item
      purchased_price = line_item[:purchased_price]

      # Add the purchased price to the total price without tax
      total_price_without_tax += purchased_price
    end

    return total_price_without_tax
  end

  def calculate_total_denominations(customer_denominations)
    total_denominations = 0
    customer_denominations.each do |denomination_value, quantity|
      total_denominations += denomination_value.to_i * quantity.to_i
    end
    total_denominations
  end

  def add_line_item
    product_id = params[:product_id]
    quantity = params[:quantity].to_i

    # Retrieve the product name based on the product_id (assuming you have a Product model)
    product = Product.find(product_id)
    product_name = product.name

    # Create a line item hash with product_id, product_name, and quantity
    line_item = { product_id: product_id, product_name: product_name, quantity: quantity }

    # Store the line item in the session
    session[:line_items] << line_item

    # Redirect back to the input page
    redirect_to input_index_path
  end

  def calculate_total_tax_payable(line_items)
    total_tax_payable = 0

    line_items.each do |line_item|
      # Retrieve the tax pay amount for the current line item
      tax_pay = line_item[:tax_pay]

      # Add the tax pay amount to the total tax payable
      total_tax_payable += tax_pay
    end

    return total_tax_payable
  end

end

app/helpers/input_helper.rb
module InputHelper
end

app/views/input/generate_bill.html.erb
<div class="background">
  <div class="main1"><h2 class="generated-bill-title">Generated Bill</h2>

    <div class="fle">
      <p class="email-field">Customer Email: </p>
      <p class="email"><%= @customer_email %></p>

    </div>

    <h3 class="bill-section-title">BILL SECTION</h3>
    <table class="bill-table">
      <thead>
      <tr>
        <th class="product-name-header">Product Name</th>
        <th class="unit-price-header">Unit Price</th>
        <th class="quantity-header">Quantity</th>
        <th class="purchased-price-header">Purchased Price</th>
        <th class="tax-header">Tax</th>
        <th class="tax-pay-header">Tax Pay</th>
        <th class="total-header">Total</th>
      </tr>
      </thead>
      <tbody>
      <% @line_items.each_with_index do |line_item, index| %>
        <tr class="line-item-row">
          <td class="product-name"><%= line_item[:product_name].capitalize() %></td>
          <td class="unit-price"><%= number_to_currency(line_item[:unit_price], unit: '₹') %></td>
          <td class="quantity"><%= line_item[:quantity] %></td>
          <td class="purchased-price"><%= number_to_currency(line_item[:purchased_price], unit: '₹') %></td>
          <td class="tax"><%= number_to_percentage(line_item[:tax], precision: 0) %></td>
          <td class="tax-pay"><%= number_to_currency(line_item[:tax_pay], unit: '₹') %></td>
          <td class="total"><%= number_to_currency(line_item[:total], unit: '₹') %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="form-group">
      <h3>BALENCE DENOMINATIONS</h3>
      <div class="form-group1">
        <div class="denomination">
          <label for="denomination_500">500</label>
          <input type="number" name="denominations[500]" id="denomination_500" class="form-control denomination-input" value="<%= @five_hundred %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_50">50</label>
          <input type="number" name="denominations[50]" id="denomination_50" class="form-control denomination-input" value="<%= @fifty %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_20">20</label>
          <input type="number" name="denominations[20]" id="denomination_20" class="form-control denomination-input" value="<%= @twenty %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_10">10</label>
          <input type="number" name="denominations[10]" id="denomination_10" class="form-control denomination-input" value="<%= @ten %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_5">5</label>
          <input type="number" name="denominations[5]" id="denomination_5" class="form-control denomination-input" value="<%= @five %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_2">2</label>
          <input type="number" name="denominations[2]" id="denomination_2" class="form-control denomination-input" value="<%= @two %>" readonly>
        </div>

        <div class="denomination">
          <label for="denomination_1">1</label>
          <input type="number" name="denominations[1]" id="denomination_1" class="form-control denomination-input" value="<%= @one %>" readonly>
        </div>
      </div>
    </div>

    <div class="end">
      <p class="total-price">Total Price Without Tax: <%= number_to_currency(@total_price_without_tax, unit: '₹') %></p>
      <p class="total-tax">Total Tax Payable: <%= number_to_currency(@total_tax_payable, unit: '₹') %></p>
      <p class="net-price">Net Price: <%= number_to_currency(@net_price, unit: '₹') %></p>
      <p class="rounded-down-value">Rounded Down Value: <%= number_to_currency(@rounded_down_value, unit: '₹') %></p>
      <p class="balance-payable">Balance Payable to
        Customer: <%= number_to_currency(@balance_payable_to_customer, unit: '₹') %></p>
    </div>
  </div>
</div>
<div class="vb-1">
  <%= link_to 'Back', root_path, class: "custom-button" %>
  <%= link_to 'Products', products_path, class: "custom-button two" %>
  <%= link_to 'New Products', new_product_path, class: "custom-button four" %>
</div>